# Generated by Django 3.1.5 on 2021-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
