# Generated by Django 3.1.5 on 2021-05-24 11:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_auto_20210524_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='ques',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=50, null=True),
        ),
    ]
