# Generated by Django 3.1.5 on 2021-05-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20210524_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='rating',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ques',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3'), ('choice4', 'choice4')], max_length=250, null=True),
        ),
    ]
