# Generated by Django 3.1.5 on 2021-05-26 18:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_auto_20210525_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='my_field2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='rating',
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques1', models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3'), ('choice4', 'choice4')], max_length=250, null=True)),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49, null=True)),
                ('comment', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=20, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.survey')),
            ],
        ),
    ]
