# Generated by Django 3.1.5 on 2021-05-28 04:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_auto_20210527_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3')], max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='ques1',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3'), ('choice4', 'choice4')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='rating',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
