# Generated by Django 3.1.5 on 2021-05-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0009_auto_20210528_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page1',
            old_name='my_field',
            new_name='p1q2',
        ),
        migrations.RenameField(
            model_name='page2',
            old_name='my_field',
            new_name='p2q2',
        ),
        migrations.RenameField(
            model_name='page3',
            old_name='my_field',
            new_name='p3q2',
        ),
        migrations.RenameField(
            model_name='page4',
            old_name='my_field',
            new_name='p4q2',
        ),
        migrations.RenameField(
            model_name='page5',
            old_name='my_field',
            new_name='p5q2',
        ),
        migrations.RemoveField(
            model_name='page1',
            name='ques1',
        ),
        migrations.RemoveField(
            model_name='page2',
            name='ques1',
        ),
        migrations.RemoveField(
            model_name='page3',
            name='ques1',
        ),
        migrations.RemoveField(
            model_name='page4',
            name='ques1',
        ),
        migrations.RemoveField(
            model_name='page5',
            name='ques1',
        ),
        migrations.AddField(
            model_name='page1',
            name='p1q1',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page2',
            name='p2q1',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page3',
            name='p3q1',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page4',
            name='p4q1',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page5',
            name='p5q1',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], max_length=250, null=True),
        ),
    ]
