# Generated by Django 3.1.5 on 2021-06-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_auto_20210531_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page1',
            old_name='comment',
            new_name='p1q3',
        ),
        migrations.RenameField(
            model_name='page1',
            old_name='rating',
            new_name='p1q4',
        ),
        migrations.RenameField(
            model_name='page2',
            old_name='comment',
            new_name='p2q3',
        ),
        migrations.RenameField(
            model_name='page2',
            old_name='rating',
            new_name='p2q4',
        ),
        migrations.RenameField(
            model_name='page3',
            old_name='comment',
            new_name='p3q3',
        ),
        migrations.RenameField(
            model_name='page3',
            old_name='rating',
            new_name='p3q4',
        ),
        migrations.RenameField(
            model_name='page4',
            old_name='comment',
            new_name='p4q3',
        ),
        migrations.RenameField(
            model_name='page4',
            old_name='rating',
            new_name='p4q4',
        ),
        migrations.RenameField(
            model_name='page5',
            old_name='comment',
            new_name='p5q3',
        ),
        migrations.RenameField(
            model_name='page5',
            old_name='rating',
            new_name='p5q4',
        ),
    ]
